# Generated by Django 2.1.7 on 2019-02-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='jogos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='pontos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='rounds_ganhos',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
